#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <errno.h>
#include <string.h>
#include <signal.h>

int main(int argc, char **argv)
{
    int pid=atoi(argv[1]);
    kill(pid, SIGINT);
    exit(EXIT_SUCCESS);

}
/*
EJERCICIO MAIN SEÑALES: IMPLEMENTAR UN PROGRAMA QUE REALICE 
EL TRATAMIENTO DE LA SEÑAL SIGUSR1, SIGINT Y SIGKILL

PROGRAMA QUE RECIBE LA SEÑAL: ANTE LA LLEGADA DE LA SEÑAL SIGUSR1 
EL PROGRAMA IMPRIMIRA POR PANTALLA QUE HA RECIBIDO LA SEÑAL SIGUSR1
CON SU CODIGO 10

ANTE LA SEÑAL SIGINT EL PROCESO DEBERA IMPRIMIR DEBERA IMPRIMAR QUE 
SE HA RECIBIDO UN CONTROL C Y ESTE FINALIZARA Y EL SIGKILL IGUAL

EJERCICIO MAIN SEÑALES 2: EL PROGRAMA QUE ENVIA LAS SEÑALES DEBERA RECIBIR 
OBLIGATORIAMENTE POR LINEA DE ARGUMENTOS EL PID DEL PROCESO AL CUAL SE LE 
ENVIARAN LAS SEÑALES Y A CONTINUACION LE ENVIARA DICHO PROCESO A LA SEÑAL
SIGUSR1, SE DORMIRA 1 SEGUNDO, LE ENVIARA LA SEÑAL SIGINT, SE DORMIRA 1 SEGUNDO 
Y POR ULTIMO LA SEÑAL SIGKILL
*/